baseURL = "https://usekarma.dev/"
title = "UseKarma"
theme = "hugo-book"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true


[params]
  BookTheme = "auto" # "light", "dark", or "auto"
  BookLogo = "assets/logo/usekarma_light_128x128.png"
  BookFavicon = "assets/logo/favicon-light.png"
  BookToC = true
  BookSection = "*"

[markup]
  [markup.goldmark.renderer]
    unsafe = true  # Allows raw HTML in markdown
